package com.bottle.com.bottle.utils;

import com.bottle.com.bottle.R;
import com.bottle.com.bottle.domain.Emojis;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * Created by lenovo on 2017/9/29.
 */

public abstract class EmojiUtils {

    private  static List<Emojis>  lists=  null ;
    private  static Map<String,Integer> emojisMap = null;
    static {
         getInstance();
    }

    public static Map<String,Integer>  getEmojisMap() {
        if( null != emojisMap ){
            return emojisMap;
        }
        Map<String,Integer> result = new HashMap<String,Integer>();
        List<Emojis> list_1 = new ArrayList<Emojis>();
        if( null != lists ){
            list_1 = lists ;
        }else{
            list_1 = getInstance();
        }
        for (int i = 0; i <list_1.size() ; i++) {
            Emojis emojis = list_1.get(i);
            result.put(emojis.name,emojis.id);
        }
        emojisMap = result ;
        return result ;
    }

     public static List<Emojis> getInstance() {
          if( null != lists ){
              return lists ;
          }
         List<Emojis> list = new ArrayList<Emojis>();
         Emojis emoji = new Emojis();
         emoji.id = R.mipmap.emotion_001;
         emoji.name="[:微笑]";
         list.add(emoji);
         Emojis emoji2 = new Emojis();
         emoji2.id = R.mipmap.emotion_002;
         emoji2.name="[:流口水]";
         list.add(emoji2);
         Emojis emoji3 = new Emojis();
         emoji3.id = R.mipmap.emotion_003;
         emoji3.name="[:色]";
         list.add(emoji3);
         Emojis emoji4 = new Emojis();
         emoji4.id = R.mipmap.emotion_004;
         emoji4.name="[:舌头]";
         list.add(emoji4);
         Emojis emoji5 = new Emojis();
         emoji5.id = R.mipmap.emotion_005;
         emoji5.name="[:叼烟]";
         list.add(emoji5);
         Emojis emoji6 = new Emojis();
         emoji6.id = R.mipmap.emotion_006;
         emoji6.name="[:哭]";
         list.add(emoji6);
         Emojis emoji7 = new Emojis();
         emoji7.id = R.mipmap.emotion_007;
         emoji7.name="[:害羞]";
         list.add(emoji7);
         Emojis emoji8 = new Emojis();
         emoji8.id = R.mipmap.emotion_008;
         emoji8.name="[:闭嘴]";
         list.add(emoji8);
         Emojis emoji9 = new Emojis();
         emoji9.id = R.mipmap.emotion_009;
         emoji9.name="[:睡觉]";
         list.add(emoji9);
         Emojis emoji10 = new Emojis();
         emoji10.id = R.mipmap.emotion_010;
         emoji10.name="[:大哭]";
         list.add(emoji10);
         Emojis emoji11 = new Emojis();
         emoji11.id = R.mipmap.emotion_011;
         emoji11.name="[:歪嘴]";
         list.add(emoji11);
         Emojis emoji12 = new Emojis();
         emoji12.id = R.mipmap.emotion_012;
         emoji12.name="[:牛气]";
         list.add(emoji12);
         Emojis emoji13 = new Emojis();
         emoji13.id = R.mipmap.emotion_013;
         emoji13.name="[:淘气]";
         list.add(emoji13);
         Emojis emoji14 = new Emojis();
         emoji14.id = R.mipmap.emotion_014;
         emoji14.name="[:大笑]";
         list.add(emoji14);
         Emojis emoji15 = new Emojis();
         emoji15.id = R.mipmap.emotion_015;
         emoji15.name="[:盯住看]";
         list.add(emoji15);
         Emojis emoji16 = new Emojis();
         emoji16.id = R.mipmap.emotion_016;
         emoji16.name="[:流汗]";
         list.add(emoji16);
         Emojis emoji17 = new Emojis();
         emoji17.id = R.mipmap.emotion_017;
         emoji17.name="[:喊喇叭]";
         list.add(emoji17);
         Emojis emoji18 = new Emojis();
         emoji18.id = R.mipmap.emotion_018;
         emoji18.name="[:闪亮]";
         list.add(emoji18);
         Emojis emoji19 = new Emojis();
         emoji19.id = R.mipmap.emotion_019;
         emoji19.name="[:你牛]";
         list.add(emoji19);
         Emojis emoji20 = new Emojis();
         emoji20.id = R.mipmap.emotion_020;
         emoji20.name="[:凶你]";
         list.add(emoji20);
         Emojis emoji21 = new Emojis();
         emoji21.id = R.mipmap.emotion_021;
         emoji21.name="[:惊讶]";
         list.add(emoji21);
         Emojis emoji22 = new Emojis();
         emoji22.id = R.mipmap.emotion_022;
         emoji22.name="[:疑问]";
         list.add(emoji22);
         Emojis emoji23 = new Emojis();
         emoji23.id = R.mipmap.emotion_023;
         emoji23.name="[:OK]";
         list.add(emoji23);
         Emojis emoji24 = new Emojis();
         emoji24.id = R.mipmap.emotion_024;
         emoji24.name="[:鼓掌]";
         list.add(emoji24);
         Emojis emoji25 = new Emojis();
         emoji25.id = R.mipmap.emotion_025;
         emoji25.name="[:握手]";
         list.add(emoji25);
         Emojis emoji26 = new Emojis();
         emoji26.id = R.mipmap.emotion_026;
         emoji26.name="[:偷笑]";
         list.add(emoji26);
         Emojis emoji27 = new Emojis();
         emoji27.id = R.mipmap.emotion_027;
         emoji27.name="[:怕怕]";
         list.add(emoji27);
         Emojis emoji28 = new Emojis();
         emoji28.id = R.mipmap.emotion_028;
         emoji28.name="[:加油]";
         list.add(emoji28) ;
         Emojis emoji29 = new Emojis();
         emoji29.id = R.mipmap.emotion_029;
         emoji29.name="[:哭了]";
         list.add(emoji29);
         Emojis emoji30 = new Emojis();
         emoji30.id = R.mipmap.emotion_030;
         emoji30.name="[:吐了]";
         list.add(emoji30);
         Emojis emoji31 = new Emojis();
         emoji31.id = R.mipmap.emotion_031;
         emoji31.name="[:晕]";
         list.add(emoji31);
         Emojis emoji32 = new Emojis();
         emoji32.id = R.mipmap.emotion_032;
         emoji32.name="[:抚摸]";
         list.add(emoji32);
         Emojis emoji33 = new Emojis();
         emoji33.id = R.mipmap.emotion_033;
         emoji33.name="[:耶]";
         list.add(emoji33);
         Emojis emoji34 = new Emojis();
         emoji34.id = R.mipmap.emotion_034;
         emoji34.name="[:飞吻]";
         list.add(emoji34);
         Emojis emoji35 = new Emojis();
         emoji35.id = R.mipmap.emotion_035;
         emoji35.name="[:好开心哦]";
         list.add(emoji35);
         Emojis emoji36 = new Emojis();
         emoji36.id = R.mipmap.emotion_036;
         emoji36.name="[:搞笑]";
         list.add(emoji36);
         Emojis emoji37 = new Emojis();
         emoji37.id = R.mipmap.emotion_037;
         emoji37.name="[:鄙视你]";
         list.add(emoji37);
         Emojis emoji38 = new Emojis();
         emoji38.id = R.mipmap.emotion_038;
         emoji38.name="[:虚]";
         list.add(emoji38);
         Emojis emoji39 = new Emojis();
         emoji39.id = R.mipmap.emotion_039;
         emoji39.name="[:绿了]";
         list.add(emoji39);
         Emojis emoji40 = new Emojis();
         emoji40.id = R.mipmap.emotion_040;
         emoji40.name="[:思考]";
         list.add(emoji40);
         Emojis emoji41 = new Emojis();
         emoji41.id = R.mipmap.emotion_041;
         emoji41.name="[:亲我]";
         list.add(emoji41);
         Emojis emoji42 = new Emojis();
         emoji42.id = R.mipmap.emotion_042;
         emoji42.name="[:不高兴]";
         list.add(emoji42);
         Emojis emoji43 = new Emojis();
         emoji43.id = R.mipmap.emotion_043;
         emoji43.name="[:大嘴巴]";
         list.add(emoji43);
         Emojis emoji44 = new Emojis();
         emoji44.id = R.mipmap.emotion_044;
         emoji44.name="[:对不起]";
         list.add(emoji44);
         Emojis emoji45 = new Emojis();
         emoji45.id = R.mipmap.emotion_045;
         emoji45.name="[:88]";
         list.add(emoji45);
         Emojis emoji46 = new Emojis();
         emoji46.id = R.mipmap.emotion_046;
         emoji46.name="[:投降]";
         list.add(emoji46);
         Emojis emoji47= new Emojis();
         emoji47.id = R.mipmap.emotion_047;
         emoji47.name="[:哼]";
         list.add(emoji47);
         Emojis emoji48 = new Emojis();
         emoji48.id = R.mipmap.emotion_048;
         emoji48.name="[:打脸]";
         list.add(emoji48);
         Emojis emoji49 = new Emojis();
         emoji49.id = R.mipmap.emotion_049;
         emoji49.name="[:恭喜]";
         list.add(emoji49);
         Emojis emoji50 = new Emojis();
         emoji50.id = R.mipmap.emotion_050;
         emoji50.name="[:羞羞]";
         list.add(emoji50);
         Emojis emoji51 = new Emojis();
         emoji51.id = R.mipmap.emotion_051;
         emoji51.name="[:馋猫]";
         list.add(emoji51);
         Emojis emoji52 = new Emojis();
         emoji52.id = R.mipmap.emotion_052;
         emoji52.name="[:叼玫瑰]";
         list.add(emoji52);
         Emojis emoji53 = new Emojis();
         emoji53.id = R.mipmap.emotion_053;
         emoji53.name="[:鄙视]";
         list.add(emoji53);
         Emojis emoji54 = new Emojis();
         emoji54 .id = R.mipmap.emotion_054 ;
         emoji54 .name="[:想钱]";
         list.add(emoji54 );
         Emojis emoji55 = new Emojis();
         emoji55.id = R.mipmap.emotion_055;
         emoji55.name="[:报告]";
         list.add(emoji55);
         Emojis emoji56 = new Emojis();
         emoji56.id = R.mipmap.emotion_056;
         emoji56.name="[:手指]";
         list.add(emoji56);
         Emojis emoji57 = new Emojis();
         emoji57.id = R.mipmap.emotion_057;
         emoji57.name="[:挤眼]";
         list.add(emoji57);
         Emojis emoji58 = new Emojis();
         emoji58.id = R.mipmap.emotion_058;
         emoji58.name="[:天使]";
         list.add(emoji58);
         Emojis emoji59 = new Emojis();
         emoji59.id = R.mipmap.emotion_059;
         emoji59.name="[:调皮了]";
         list.add(emoji59);
         Emojis emoji60 = new Emojis();
         emoji60.id = R.mipmap.emotion_060;
         emoji60.name="[:叹气]";
         list.add(emoji60);
         Emojis emoji61 = new Emojis();
         emoji61.id = R.mipmap.emotion_061;
         emoji61.name="[:黑眼圈]";
         list.add(emoji61);
         Emojis emoji62 = new Emojis();
         emoji62.id = R.mipmap.emotion_062;
         emoji62.name="[:生病了]";
         list.add(emoji62);
         Emojis emoji63 = new Emojis();
         emoji63.id = R.mipmap.emotion_063;
         emoji63.name="[:坏笑]";
         list.add(emoji63);
         Emojis emoji64 = new Emojis();
         emoji64.id = R.mipmap.emotion_064;
         emoji64.name="[:算账]";
         list.add(emoji64);
         Emojis emoji65 = new Emojis();
         emoji65.id = R.mipmap.emotion_065;
         emoji65.name="[:被打]";
         list.add(emoji65);
         Emojis emoji66 = new Emojis();
         emoji66.id = R.mipmap.emotion_066;
         emoji66.name="[:蒙面]";
         list.add(emoji66);
         Emojis emoji67 = new Emojis();
         emoji67.id = R.mipmap.emotion_067;
         emoji67.name="[:炸弹]";
         list.add(emoji67);
         Emojis emoji68 = new Emojis();
         emoji68.id = R.mipmap.emotion_068;
         emoji68.name="[:信件]";
         list.add(emoji68);
         Emojis emoji69 = new Emojis();
         emoji69.id = R.mipmap.emotion_069;
         emoji69.name="[:手机]";
         list.add(emoji69);
         Emojis emoji70 = new Emojis();
         emoji70.id = R.mipmap.emotion_070;
         emoji70.name="[:礼物]";
         list.add(emoji70);
         Emojis emoji71 = new Emojis();
         emoji71.id = R.mipmap.emotion_071;
         emoji71.name="[:爱心]";
         list.add(emoji71);
         Emojis emoji72 = new Emojis();
         emoji72.id = R.mipmap.emotion_072;
         emoji72.name="[:心碎]";
         list.add(emoji72);
         Emojis emoji73 = new Emojis();
         emoji73.id = R.mipmap.emotion_073;
         emoji73.name="[:吻]";
         list.add(emoji73);
         Emojis emoji74 = new Emojis();
         emoji74.id = R.mipmap.emotion_074;
         emoji74.name="[:玫瑰花]";
         list.add(emoji74);
         Emojis emoji75 = new Emojis();
         emoji75.id = R.mipmap.emotion_075;
         emoji75.name="[:凋谢]";
         list.add(emoji75);
         Emojis emoji76 = new Emojis();
         emoji76.id = R.mipmap.emotion_076;
         emoji76.name="[:飞机]";
         list.add(emoji76);
         Emojis emoji77 = new Emojis();
         emoji77.id = R.mipmap.emotion_077;
         emoji77.name="[:茶]";
         list.add(emoji77);
         Emojis emoji78 = new Emojis();
         emoji78.id = R.mipmap.emotion_078;
         emoji78.name="[:棒棒滴]";
         list.add(emoji78);
         Emojis f_static_000 = new Emojis();
         f_static_000.id = R.mipmap.f_static_000;
         f_static_000.name="[:呵呵]";
         list.add(f_static_000);
         Emojis f_static_001 = new Emojis();
         f_static_001.id = R.mipmap.f_static_001;
         f_static_001.name="[:吐舌头]";
         list.add(f_static_001);
         Emojis f_static_002 = new Emojis();
         f_static_002.id = R.mipmap.f_static_002;
         f_static_002.name="[:汗颜]";
         list.add(f_static_002);
         Emojis f_static_003 = new Emojis();
         f_static_003.id = R.mipmap.f_static_003;
         f_static_003.name="[:捂住笑]";
         list.add(f_static_003);
         Emojis f_static_004 = new Emojis();
         f_static_004.id = R.mipmap.f_static_004;
         f_static_004.name="[:再见了]";
         list.add(f_static_004);
         Emojis f_static_005 = new Emojis();
         f_static_005.id = R.mipmap.f_static_005;
         f_static_005.name="[:打头]";
         list.add(f_static_005);
         Emojis f_static_006 = new Emojis();
         f_static_006.id = R.mipmap.f_static_006;
         f_static_006.name="[:摸汗]";
         list.add(f_static_006);
         Emojis f_static_007 = new Emojis();
         f_static_007.id = R.mipmap.f_static_007;
         f_static_007.name="[:猪头]";
         list.add(f_static_007);
         Emojis f_static_008 = new Emojis();
         f_static_008.id = R.mipmap.f_static_008;
         f_static_008.name="[:玫瑰玫瑰]";
         list.add(f_static_008);
         Emojis f_static_009 = new Emojis();
         f_static_009.id = R.mipmap.f_static_009;
         f_static_009.name="[:伤心]";
         list.add(f_static_009);
         Emojis f_static_010 = new Emojis();
         f_static_010.id = R.mipmap.f_static_010;
         f_static_010.name="[:哭泣]";
         list.add(f_static_010);
         Emojis f_static_011 = new Emojis();
         f_static_011.id = R.mipmap.f_static_011;
         f_static_011.name="[:别说话]";
         list.add(f_static_011);
         Emojis f_static_012 = new Emojis();
         f_static_012.id = R.mipmap.f_static_012;
         f_static_012.name="[:墨镜]";
         list.add(f_static_012);
         Emojis f_static_013 = new Emojis();
         f_static_013.id = R.mipmap.f_static_013;
         f_static_013.name="[:愤怒]";
         list.add(f_static_013);
         Emojis f_static_014 = new Emojis();
         f_static_014.id = R.mipmap.f_static_014;
         f_static_014.name="[:挤鼻子]";
         list.add(f_static_014);
         Emojis f_static_015 = new Emojis();
         f_static_015.id = R.mipmap.f_static_015;
         f_static_015.name="[:答辩]";
         list.add(f_static_015);
         Emojis f_static_016 = new Emojis();
         f_static_016.id = R.mipmap.f_static_016;
         f_static_016.name="[:黑炸弹]";
         list.add(f_static_016);
         Emojis f_static_017 = new Emojis();
         f_static_017.id = R.mipmap.f_static_017;
         f_static_017.name="[:砍]";
         list.add(f_static_017);
         Emojis f_static_018 = new Emojis();
         f_static_018.id = R.mipmap.f_static_018;
         f_static_018.name="[:卖萌]";
         list.add(f_static_018);
         Emojis f_static_019 = new Emojis();
         f_static_019.id = R.mipmap.f_static_019;
         f_static_019.name="[:色色]";
         list.add(f_static_019);
         Emojis f_static_020 = new Emojis();
         f_static_020.id = R.mipmap.f_static_020;
         f_static_020.name="[:害羞了]";
         list.add(f_static_020);
         Emojis f_static_021 = new Emojis();
         f_static_021.id = R.mipmap.f_static_021;
         f_static_021.name="[:得意]";
         list.add(f_static_021);
         Emojis f_static_022= new Emojis();
         f_static_022.id = R.mipmap.f_static_022;
         f_static_022.name="[:吐]";
         list.add(f_static_022);
         Emojis f_static_023 = new Emojis();
         f_static_023.id = R.mipmap.f_static_023;
         f_static_023.name="[:额]";
         list.add(f_static_023);
         Emojis f_static_024 = new Emojis();
         f_static_024.id = R.mipmap.f_static_024;
         f_static_024.name="[:怒火]";
         list.add(f_static_024);
         Emojis f_static_025 = new Emojis();
         f_static_025.id = R.mipmap.f_static_025;
         f_static_025.name="[:怒汗]";
         list.add(f_static_025);
         Emojis f_static_026 = new Emojis();
         f_static_026.id = R.mipmap.f_static_026;
         f_static_026.name="[:惊恐]";
         list.add(f_static_026);
         Emojis f_static_027 = new Emojis();
         f_static_027.id = R.mipmap.f_static_027;
         f_static_027.name="[:流汗了]";
         list.add(f_static_027);
         Emojis f_static_028 = new Emojis();
         f_static_028.id = R.mipmap.f_static_028;
         f_static_028.name="[:心]";
         list.add(f_static_028);
         Emojis f_static_029 = new Emojis();
         f_static_029.id = R.mipmap.f_static_029;
         f_static_029.name="[:嘴唇]";
         list.add(f_static_029);
         Emojis f_static_030 = new Emojis();
         f_static_030.id = R.mipmap.f_static_030;
         f_static_030.name="[:随便你]";
         list.add(f_static_030);
         Emojis f_static_031 = new Emojis();
         f_static_031.id = R.mipmap.f_static_031;
         f_static_031.name="[:我生气]";
         list.add(f_static_031);
         Emojis f_static_032 = new Emojis();
         f_static_032.id = R.mipmap.f_static_032;
         f_static_032.name="[:委屈了]";
         list.add(f_static_032);
         Emojis f_static_033 = new Emojis();
         f_static_033.id = R.mipmap.f_static_033;
         f_static_033.name="[:不会吧]";
         list.add(f_static_033);
         Emojis f_static_034 = new Emojis();
         f_static_034.id = R.mipmap.f_static_034;
         f_static_034.name="[:疑问了]";
         list.add(f_static_034);
         Emojis f_static_035 = new Emojis();
         f_static_035.id = R.mipmap.f_static_035;
         f_static_035.name="[:瞌睡了]";
         list.add(f_static_035);
         Emojis f_static_036 = new Emojis();
         f_static_036.id = R.mipmap.f_static_036;
         f_static_036.name="[:嘟嘟嘴]";
         list.add(f_static_036);
         Emojis f_static_037 = new Emojis();
         f_static_037.id = R.mipmap.f_static_037;
         f_static_037.name="[:啊哈哈]";
         list.add(f_static_037);
         Emojis f_static_038 = new Emojis();
         f_static_038.id = R.mipmap.f_static_038;
         f_static_038.name="[:爱心企鹅]";
         list.add(f_static_038);
         Emojis f_static_039 = new Emojis();
         f_static_039.id = R.mipmap.f_static_039;
         f_static_039.name="[:骷髅头]";
         list.add(f_static_039);
         Emojis f_static_040 = new Emojis();
         f_static_040.id = R.mipmap.f_static_040;
         f_static_040.name="[:最委屈]";
         list.add(f_static_040);
         Emojis f_static_041= new Emojis();
         f_static_041.id = R.mipmap.f_static_041;
         f_static_041.name="[:淫笑]";
         list.add(f_static_041);
         Emojis f_static_042 = new Emojis();
         f_static_042.id = R.mipmap.f_static_042;
         f_static_042.name="[:努力]";
         list.add(f_static_042);
         Emojis f_static_043 = new Emojis();
         f_static_043.id = R.mipmap.f_static_043;
         f_static_043.name="[:流鼻涕]";
         list.add(f_static_043);
         Emojis f_static_044 = new Emojis();
         f_static_044.id = R.mipmap.f_static_044;
         f_static_044.name="[:右哼哼]";
         list.add(f_static_044);
         Emojis f_static_045 = new Emojis();
         f_static_045.id = R.mipmap.f_static_045;
         f_static_045.name="[:抱抱]";
         list.add(f_static_045);
         Emojis f_static_046 = new Emojis();
         f_static_046.id = R.mipmap.f_static_046;
         f_static_046.name="[:我得意]";
         list.add(f_static_046);
         Emojis f_static_047 = new Emojis();
         f_static_047.id = R.mipmap.f_static_047;
         f_static_047.name="[:飞吻走起]";
         list.add(f_static_047);
         Emojis f_static_048 = new Emojis();
         f_static_048.id = R.mipmap.f_static_048;
         f_static_048.name="[:鄙视鄙视]";
         list.add(f_static_048);
         Emojis f_static_049 = new Emojis();
         f_static_049.id = R.mipmap.f_static_049;
         f_static_049.name="[:晕倒 ]";
         list.add(f_static_049);
         Emojis f_static_050 = new Emojis();
         f_static_050.id = R.mipmap.f_static_050;
         f_static_050.name="[:大兵]";
         list.add(f_static_050);
         Emojis f_static_051 = new Emojis();
         f_static_051.id = R.mipmap.f_static_051;
         f_static_051.name="[:绝望]";
         list.add(f_static_051);
         Emojis f_static_052 = new Emojis();
         f_static_052.id = R.mipmap.f_static_052;
         f_static_052.name="[:你很棒棒]";
         list.add(f_static_052);
         Emojis f_static_053 = new Emojis();
         f_static_053.id = R.mipmap.f_static_053;
         f_static_053.name="[:看不起你]";
         list.add(f_static_053);
         Emojis f_static_054 = new Emojis();
         f_static_054.id = R.mipmap.f_static_054;
         f_static_054.name="[:握手你好]";
         list.add(f_static_054);
         Emojis f_static_055 = new Emojis();
         f_static_055.id = R.mipmap.f_static_055;
         f_static_055.name="[:胜利]";
         list.add(f_static_055);
         Emojis f_static_056 = new Emojis();
         f_static_056.id = R.mipmap.f_static_056;
         f_static_056.name="[:佩服]";
         list.add(f_static_056);
         Emojis f_static_057 = new Emojis();
         f_static_057.id = R.mipmap.f_static_057;
         f_static_057.name="[:玫瑰凋谢]";
         list.add(f_static_057);
         Emojis f_static_058 = new Emojis();
         f_static_058.id = R.mipmap.f_static_058;
         f_static_058.name="[:吃饭]";
         list.add(f_static_058);
         Emojis f_static_059 = new Emojis();
         f_static_059.id = R.mipmap.f_static_059;
         f_static_059.name="[:蛋糕]";
         list.add(f_static_059);
         Emojis f_static_060 = new Emojis();
         f_static_060.id = R.mipmap.f_static_060;
         f_static_060.name="[:西瓜]";
         list.add(f_static_060);
         Emojis f_static_061 = new Emojis();
         f_static_061.id = R.mipmap.f_static_061;
         f_static_061.name="[:茶水]";
         list.add(f_static_061);
         Emojis f_static_062 = new Emojis();
         f_static_062.id = R.mipmap.f_static_062;
         f_static_062.name="[:甲壳虫]";
         list.add(f_static_062);
         Emojis f_static_063 = new Emojis();
         f_static_063.id = R.mipmap.f_static_063;
         f_static_063.name="[:勾引]";
         list.add(f_static_063);
         Emojis f_static_064 = new Emojis();
         f_static_064.id = R.mipmap.f_static_064;
         f_static_064.name="[:哦了]";
         list.add(f_static_064);
         Emojis f_static_065 = new Emojis();
         f_static_065.id = R.mipmap.f_static_065;
         f_static_065.name="[:动作]";
         list.add(f_static_065);
         Emojis f_static_066= new Emojis();
         f_static_066.id = R.mipmap.f_static_066;
         f_static_066.name="[:咖啡]";
         list.add(f_static_066);
         Emojis f_static_067 = new Emojis();
         f_static_067.id = R.mipmap.f_static_067;
         f_static_067.name="[:金钱]";
         list.add(f_static_067);
         Emojis f_static_068 = new Emojis();
         f_static_068.id = R.mipmap.f_static_068;
         f_static_068.name="[:月亮]";
         list.add(f_static_068);
         Emojis f_static_069 = new Emojis();
         f_static_069.id = R.mipmap.f_static_069;
         f_static_069.name="[:美女]";
         list.add(f_static_069);
         Emojis f_static_070 = new Emojis();
         f_static_070.id = R.mipmap.f_static_070;
         f_static_070.name="[:杀]";
         list.add(f_static_070);
         Emojis f_static_071 = new Emojis();
         f_static_071.id = R.mipmap.f_static_071;
         f_static_071.name="[:吓瘫]";
         list.add(f_static_071);
         Emojis f_static_072 = new Emojis();
         f_static_072.id = R.mipmap.f_static_072;
         f_static_072.name="[:小气鬼]";
         list.add(f_static_072);
         Emojis f_static_073 = new Emojis();
         f_static_073.id = R.mipmap.f_static_073;
         f_static_073.name="[:加油哦]";
         list.add(f_static_073);
         Emojis f_static_074 = new Emojis();
         f_static_074.id = R.mipmap.f_static_074;
         f_static_074.name="[:我心碎]";
         list.add(f_static_074);
         Emojis f_static_075 = new Emojis();
         f_static_075.id = R.mipmap.f_static_075;
         f_static_075.name="[:大太阳]";
         list.add(f_static_075);
         Emojis f_static_076 = new Emojis();
         f_static_076.id = R.mipmap.f_static_076;
         f_static_076.name="[:小礼物]";
         list.add(f_static_076);
         Emojis f_static_077 = new Emojis();
         f_static_077.id = R.mipmap.f_static_077;
         f_static_077.name="[:足球]";
         list.add(f_static_077);
         Emojis f_static_078 = new Emojis();
         f_static_078.id = R.mipmap.f_static_078;
         f_static_078.name="[:骷髅]";
         list.add(f_static_078);
         Emojis f_static_079 = new Emojis();
         f_static_079.id = R.mipmap.f_static_079;
         f_static_079.name="[:举旗]";
         list.add(f_static_079);
         Emojis f_static_080 = new Emojis();
         f_static_080.id = R.mipmap.f_static_080;
         f_static_080.name="[:闪电一个]";
         list.add(f_static_080);
         Emojis f_static_081 = new Emojis();
         f_static_081.id = R.mipmap.f_static_081;
         f_static_081.name="[:小馋猫]";
         list.add(f_static_081);
         Emojis f_static_082 = new Emojis();
         f_static_082.id = R.mipmap.f_static_082;
         f_static_082.name="[:眼袋]";
         list.add(f_static_082);
         Emojis f_static_083 = new Emojis();
         f_static_083.id = R.mipmap.f_static_083;
         f_static_083.name="[:臭骂]";
         list.add(f_static_083);
         Emojis f_static_084 = new Emojis();
         f_static_084.id = R.mipmap.f_static_084;
         f_static_084.name="[:气死了]";
         list.add(f_static_084);
         Emojis f_static_085 = new Emojis();
         f_static_085.id = R.mipmap.f_static_085;
         f_static_085.name="[:抠鼻屎]";
         list.add(f_static_085);
         Emojis f_static_086 = new Emojis();
         f_static_086.id = R.mipmap.f_static_086;
         f_static_086.name="[:鼓掌了]";
         list.add(f_static_086);
         Emojis f_static_087 = new Emojis();
         f_static_087.id = R.mipmap.f_static_087;
         f_static_087.name="[:嘟嘴滴汗]";
         list.add(f_static_087);
         Emojis f_static_088 = new Emojis();
         f_static_088.id = R.mipmap.f_static_088;
         f_static_088.name="[:不理你了]";
         list.add(f_static_088);
         Emojis f_static_089= new Emojis();
         f_static_089.id = R.mipmap.f_static_089;
         f_static_089.name="[:想睡觉]";
         list.add(f_static_089);
         Emojis f_static_090 = new Emojis();
         f_static_090.id = R.mipmap.f_static_090;
         f_static_090.name="[:我委屈了]";
         list.add(f_static_090);
         Emojis f_static_091 = new Emojis();
         f_static_091.id = R.mipmap.f_static_091;
         f_static_091.name="[:吓住]";
         list.add(f_static_091);
         Emojis f_static_092 = new Emojis();
         f_static_092.id = R.mipmap.f_static_092;
         f_static_092.name="[:篮球]";
         list.add(f_static_092);
         Emojis f_static_093 = new Emojis();
         f_static_093.id = R.mipmap.f_static_093;
         f_static_093.name="[:乒乓]";
         list.add(f_static_093);
         Emojis f_static_094 = new Emojis();
         f_static_094.id = R.mipmap.f_static_094;
         f_static_094.name="[:不行]";
         list.add(f_static_094);
         Emojis f_static_095 = new Emojis();
         f_static_095.id = R.mipmap.f_static_095;
         f_static_095.name="[:晃晃]";
         list.add(f_static_095);
         Emojis f_static_096 = new Emojis();
         f_static_096.id = R.mipmap.f_static_096;
         f_static_096.name="[:大叫]";
         list.add(f_static_096);
         Emojis f_static_097 = new Emojis();
         f_static_097.id = R.mipmap.f_static_097;
         f_static_097.name="[:练功]";
         list.add(f_static_097);
         Emojis f_static_098 = new Emojis();
         f_static_098.id = R.mipmap.f_static_098;
         f_static_098.name="[:看地]";
         list.add(f_static_098);
         Emojis f_static_099 = new Emojis();
         f_static_099.id = R.mipmap.f_static_099;
         f_static_099.name="[:背后]";
         list.add(f_static_099);
         Emojis f_static_0100 = new Emojis();
         f_static_0100.id = R.mipmap.f_static_100;
         f_static_0100.name="[:跳绳]";
         list.add(f_static_0100);
         Emojis f_static_0101 = new Emojis();
         f_static_0101.id = R.mipmap.f_static_101;
         f_static_0101.name="[:开心跳]";
         list.add(f_static_0101);
         Emojis f_static_0102 = new Emojis();
         f_static_097.id = R.mipmap.f_static_102;
         f_static_0102.name="[:跳]";
         list.add(f_static_0102);
         Emojis f_static_0103 = new Emojis();
         f_static_0103.id = R.mipmap.f_static_103;
         f_static_0103.name="[:碰]";
         list.add(f_static_0103);
         Emojis f_static_0104= new Emojis();
         f_static_0104.id = R.mipmap.f_static_104;
         f_static_0104.name="[:右]";
         list.add(f_static_0104);
         Emojis f_static_0105 = new Emojis();
         f_static_0105.id = R.mipmap.f_static_105;
         f_static_0105.name="[:左]";
         list.add(f_static_0105);
         Emojis f_static_0106 = new Emojis();
         f_static_0106.id = R.mipmap.f_static_106;
         f_static_0106.name="[:你闭嘴]";
         list.add(f_static_0106);
         lists = list ;


        return list;
    }
}
